export const ADD_ITEM_TO_GROCERY_LIST = "ADD_ITEM_TO_GROCERY_LIST";

export const DELETE_ITEM_FROM_GROCERY_LIST = "DELETE_ITEM_FROM_GROCERY_LIST";

export const UPDATE_ITEM_TITLE_IN_GROCERY_LIST = "UPDATE_ITEM_TILE_IN_GROCERY_LIST";

export const UPDATE_ITEM_COMPLETION_IN_GROCERY_LIST = "UPDATE_ITEM_COMPLETION_IN_GROCERY_LIST";