export const ADD_ITEM_TO_GROCERY_LIST = "ADD_ITEM_TO_GROCERY_LIST";

export const DELETE_ITEM_FROM_GROCERY_LIST = "DELETE_ITEM_FROM_GROCERY_LIST";

export const UPDATE_ITEM_TITLE_IN_GROCERY_LIST = "UPDATE_ITEM_TILE_IN_GROCERY_LIST";

export const UPDATE_ITEM_COMPLETION_IN_GROCERY_LIST = "UPDATE_ITEM_COMPLETION_IN_GROCERY_LIST";

export const ADD_NOTE = "ADD_NOTE";

export const UPDATE_NOTE_TITLE = "UPADTE_NOTE_TITLE";

export const UPDATE_NOTE_DESCRIPTION = "UPDATE_NOTE_DESCRIPTION";

export const DELETE_NOTE = 'DELETE_NOTE';

export const LOGIN_USER = 'LOGIN_USER';

export const LOGOUT_USER = 'LOGOUT_USER'